name: fltr_m_001_random_meal_generator
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.5.0-18.0.dev <4.0.0'

dependencies:
  challenge_tag:
    git:
      url: https://github.com/Soko9/challenge_tag.git
      ref: main
  flutter:
    sdk: flutter
  http: ^1.2.1
  youtube_player_flutter: ^9.0.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Futura
      fonts:
        - asset: fonts/Futura-Book.ttf
